version: "3.7"
services:
  keycloak:
    image: atom/keycloak
    container_name: atom_keycloak
    build: .
    ports:
      - "9009:8080"
      - "9010:8443"
      - "8787:8787"
    environment:
      - KEYCLOAK_ADMIN_PASSWORD=${KC_ADMIN_PASSWORD}
      - KEYCLOAK_ADMIN=${KC_ADMIN_NAME}
      - KC_DB=${KC_DB}
      - KC_DB_URL=${KC_DB_URL}
      - KC_DB_USERNAME=${KC_DB_USERNAME}
      - KC_DB_PASSWORD=${KC_DB_PASSWORD}
    networks:
      - base-network

networks:
  base-network:
    external: true
      
